### ISSUE TITLE
Print skærer qr-koder over

### ISSUE THREAD

**Issue by chrdias** [davsebamse/SmsServer#59]
[poster.pdf](https://github.com/davsebamse/SmsServer/files/545831/poster.pdf)

**Comment by davsebamse** [comment]
Prøv at lave et dummy hold, eller slet testholdet. Se om det hjælper. Det er noget css, så jeg skal rode ret meget med det er jeg bange for :-(

**Comment by davsebamse** [comment]
Prøv evt. også en anden browser.

**Comment by chrdias** [comment]
Det ser bedre ud, nu hvor jeg har slettet testholdet. Der er ingen kode,
der bliver klippet over, men holdnavn og kode kan godt komme til at stå på
to forskellige sider. Det er ikke så godt...
Jeg har også prøvet i IE og Edge, og der går det helt galt. Når der er
flere sider med koder i en blok, så printes kun den første side.

**Comment by davsebamse** [comment]
Også med seneste release? Den skulle gerne kun lave 9 qr koder per side.

**Comment by chrdias** [comment]
Nej, det er fikset nu. Har bare ikke lukket buggen

Den 25/10/2016 20.39 skrev "Davse Bamse" <notifications@github.com>:
